### ISSUE TITLE
Add support for discovery on multiple interfaces

### ISSUE THREAD

**Issue by ibookstein** [videolabs/libmicrodns#11]
See [here](https://trac.videolan.org/vlc/ticket/17477).
I'll submit a proper pull request if no one beats me to the punch and I find the time to do it.

**Comment by jbkempf** [comment]
Good idea.

**Comment by pfolk** [comment]
DoomMuffins, I read your comment in the related VLC issue, and wanted to understand: is your proposal to create multiple sockets in mdns_init, store them all in mdns_ctx, and do a select()/recv() instead of recv() , and for(){sendto()} instead of simply sendto() in mdns.c?  Is this all only relevant for Windows?

**Comment by pfolk** [comment]
For context, VLC issue is at https://trac.videolan.org/vlc/ticket/17477
As I understand it this is a showstopper for VLC Chromecast support under Windows.

**Comment by ibookstein** [comment]
Regarding whether it's a showstopper or not, it prevents active discovery of services on networks to which the computer is connected via a secondary network interface. The query packet is simply sent once on a single network interface. I think the problem should surface on Unix systems as well, but I'm not sure. My computer's problem of defaulting to the loopback interface is specific, and should not surface often.
Whether it's a showstopper or not I can't judge, because I don't know how common the scenario of accessing devices through secondary network interfaces is.
Regarding the implementation you propose - that sounds about right, moving the blocking timeout on the reply from the recv to the select.

**Comment by ibookstein** [comment]
Note that determining the amount of required sockets and the interface indices to which they should each be configured via `setsockopt(IP_MULTICAST_IF)` is OS-specific as far as I can tell (Chromium has several separate implementations - `GetAdaptersAddresses`, netlink sockets, `getifaddrs`, and another thing on Darwin which I can't remember.

**Comment by pfolk** [comment]
For the record, my computer also defaults to loopback under Windows 10. I would guess that the default adapter is the first adapter, which is most likely the loopback...

**Comment by ibookstein** [comment]
My motherboard has two network adapters. When the Ethernet cable was connected to the 'primary' one the packet defaulted to it. When the Ethernet cable was connected to the 'secondary' one, the packet defaulted to loopback. I'm guessing it's a bug in WinSock / Windows' TCP Stack.

**Comment by ibookstein** [comment]
What I think the cleanest way to do this is adding a `get_interfaces` function to the `compat.c` module, which would return an array of interface indices for use with `setsockopt(IP_MULTICAST_IF)`.
Internally, there would be a different implementation for each platform.
It may bring the `compat.c` module to a situation where it's justified to split it into `compat_win32.c`, `compat_unix.c`, etc., instead of all the conditional compilation stuff.

**Comment by chouquette** [comment]
Hi,

Could you try with PR #14 ? It should fix your issue, but I wouldn't mind the extra tests :)

There's probably quite a few things to cleanup, and it might conflict with the PR you sent, which I didn't see. If all works for you, I'll rebase everything locally and push

**Comment by jbkempf** [comment]
Ping @DoomMuffins

**Comment by ibookstein** [comment]
Cool, I'll give it a shot when I find the time (any idea whether the change is already upstream in VLC's nightly or my only way to test it is via compiling and writing client code myself?)

**Comment by chouquette** [comment]
It will be part of tonight's nightly build!

**Comment by merarischroeder** [comment]
This is still a problem for me. I've got:

- Windows 10 x64

Network interfaces:

- Built-in ethernet adaptor with a broken plug port
- WiFi
- 2x VMware virtual ethernet adapters.
- USB Ethernet plug (Comsol Gigabit)

When I have the USB Ethernet plug connected the scan fails to find the chromecast. With the USB Ethernet adaptor unplugged it works fine. But I prefer to use ethernet to leave WiFi for mobile phone devices in the office.

When I leave the USB Ethernet Plugin:
- If I disable the build-in ethernet adaptor, it doesn't work, only if I unplug the USB Ethernet Adaptor.
- If I also manually disable the WiFi adaptor, it does work. When the adaptor is on, Windows is using the ethernet adaptor, but having the WiFi preconnected for when ethernet is disconnected.

For now, my workaround is to manually disable other adaptors (including WiFi). This wouldn't be intuitive for general users though.

**Comment by chouquette** [comment]
How are you testing those changes? Is there a chance you could add a few debug statements here and there to help us track the potential issue?

**Comment by merarischroeder** [comment]
Unlikely, I imagine that would require compiling it myself. I'm too time poor at the moment for that, sorry. 

But if that means simply getting the debug edition and returning log files, that's more likely.

**Comment by chouquette** [comment]
Are you currently testing with a VLC nightly build? If so, which version

**Comment by merarischroeder** [comment]
vlc-3.0.0-20170411-1225-git-win64

**Comment by merarischroeder** [comment]
I've got debug version now installed "vlc-3.0.0-20170412-0508-git-win64-debug\vlc-3.0.0-git"

I'm testing debugging, and can see output logs in Visual Studio (after attaching to process)

**Comment by chouquette** [comment]
So to summarize:
- The VirtualBox interfaces are irrelevent here (which is a good news)
- You're connected through WiFi to the network that contains a chromecast
- You're also connected through ethernet (using an USB->Ethernet adapter) to the same network
- It only detects the chromecast when a single network adapter is connected to the proper network

I should be able to replicate such a setup, if this is correct.

**Comment by merarischroeder** [comment]
Confirmed. Either i) Wifi, or ii) USB->Ethernet adapter. But not both.

**Comment by chouquette** [comment]
Ok I can reproduce somehow, but results are strange.
I now also have:
- A disconnected ethernet adapter
- A connected wifi adapter
- A connected USB/ethernet adapter
Both connected adapters on the same network. It doesn't discover anything. 

However, when I unplugged the USB/ethernet adapter and relaunched the test program, the Windows Firewall popup appeared, and accepting the network connection lead to a bunch of devices being discovered. Replugging the USB/ethernet adapter now works, as the test program has been authorized to perform network operation.

Recompiling the test program will cause it to not be recognized by windows firewall (I assume) and now the same problem happens again.

**Comment by chouquette** [comment]
It should now be fixed, please try again with http://people.videolan.org/~hugo/vlc-3.0-mdns.zip !

**Comment by merarischroeder** [comment]
I had wifi disconnected (enabled but no wifi SSID connected). It wasn't working. I tried a lot of combinations and found that:

- It works with WiFi adapter disabled (even though it wasn't SSID connected)
- It works with the secondary Ethernet enabled (as long as the WiFi adapter is disabled)

Also, as a one off, it seemed to work with all three active, but I couldn't reproduce again. I also had it opened [As Administrator] at the time, but I don't think that's significant. It was a one-off, and all three adapters were active at the time.

**Comment by merarischroeder** [comment]
I'm happy to do some testing directly on a standalone microdns console application, and maybe you can include PDB file. With line by line debugging, I can see how it works, and help out a lot.

I'm mainly a C# coder, coding since I was 7 (now 30). I'm very familiar with networking protocols, and recently used the IP Helper API with C#.

I've never developed anything serious in C++. Although I do publish the Windows version of the Poppler pdf library on blog.alivate.com.au

**Comment by chouquette** [comment]
Yeah I screwed doing the test build :)
I updated the build, it should work better now

**Comment by merarischroeder** [comment]
Same link?

**Comment by chouquette** [comment]
Same link

**Comment by chouquette** [comment]
@merarischroeder Did you give the build a try?
