### ISSUE TITLE
Talos Security Advisory for videolabs (TALOS-2020-0994-0996)

### ISSUE THREAD

**Issue by CiscoTalos** [videolabs/libmicrodns#28]
Hello, 
The Cisco Talos team found security vulnerabilities affecting videolabs. As this is a sensitive security issue, please provide an email address & PGP key or mark this issue as private.  Please acknowledge receipt of this message so we can confirm we have the correct method for reporting security issues.

For further information about the Cisco Vendor Vulnerability Reporting and Disclosure Policy please refer to this document which also links to our public PGP key. https://tools.cisco.com/security/center/resources/vendor_vulnerability_policy.html

Please CC vulndev@cisco.com on all correspondence related to this issue.

**Comment by chouquette** [comment]
Hi,

You can contact me at hugo@videolan.org using this PGP key: https://keybase.io/chouquette/pgp_keys.asc?fingerprint=9477e0d31426892d23619994df8480a4e3cf72eb

**Comment by CiscoTalos** [comment]
Thanks. Will send now.

**Comment by CiscoTalos** [comment]
Hello,
Is there a status update or any development on this issue?

**Comment by chouquette** [comment]
Hi,

All issues are fixed but are awaiting a coordinated release with VLC.
I reached out to you through email a few minutes ago, and will close the ticket when the fixes are released

Thanks,

**Comment by chouquette** [comment]
All fixes were pushed and 0.1.1 was tagged.

Thanks a lot for reporting these issues, and allowing us to find more :)
