### ISSUE TITLE
Change name of strrcmp() function

### ISSUE THREAD

**Issue by hadess** [videolabs/libmicrodns#42]
I was looking through the libmicrodns code, and I was really confused by `strrcmp()`, which seems to be misnamed, hence my confusion.

```c
static int 
strrcmp(const char *s1, const char *s2)
```

If I understood the code correctly, it checks that the the last `strlen(s2)` characters of `s1` are the same as `s2`. The function also doesn't ever return `-1` which means it's not really a variants of `strcmp()`.

Given all that, could the function be changed to something like:
```c
static bool
str_has_prefix(const char *str, const char *prefix)
```

I'm happy to make that change myself, I will need to make some more changes for A/AAAA queries support.

**Comment by hadess** [comment]
Another implementation of `strrcmp()` which has a completely different behaviour: https://github.com/Arkq/kollector/blob/master/src/strrcmp.c

It matches the behaviour of [the implementation in the Linux kernel](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/scripts/mod/modpost.c#n795), though it has clearer names for the arguments, and needs a comment to explain what it does.

**Comment by jbkempf** [comment]
I doubt anyone really cares about this. Following the kernel is the best idea, though.

**Comment by hadess** [comment]
> I doubt anyone really cares about this.

I was annoyed that it took me this long to figure out what it did, so past me cares ;)

**Comment by jbkempf** [comment]
> > I doubt anyone really cares about this.
> 
> I was annoyed that it took me this long to figure out what it did, so past me cares ;)

Fair enough.
